# build.yaml - Updated for SuperMini nRF52840
include:
  - board: supermini_nrf52840  # or whatever the correct board name is
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: supermini_nrf52840
    shield: lily58_right