# build.yaml - Studio support with Sharp MIP displays
include:
  - board: nice_nano_v2
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DDTC_OVERLAY_FILE="lily58_mip.overlay"
  - board: nice_nano_v2
    shield: lily58_right
    cmake-args: -DDTC_OVERLAY_FILE="lily58_mip.overlay"