# build.yaml - Studio support for SuperMini nRF52840 controllers
include:
  - board: supermini_nrf52840
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: supermini_nrf52840
    shield: lily58_right