# build.yaml - Properly configured for ZMK Studio
include:
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view