# build.yaml - SuperMini nRF52840 using nice_nano_v2 compatibility
include:
  - board: nice_nano_v2
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: lily58_right