
# build.yaml - Using standard nice_view to use custom logo
include:
  # Regular builds
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
  
  # Settings reset builds (add these temporarily)
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_left
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_right