# build.yaml - Studio support for SuperMini nRF52840 controllers
# SuperMini controllers use the nice_nano_v2 board definition
include:
  - board: nice_nano_v2
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: lily58_right