CONFIG_ZMK_BLE=y
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_PHY_2M=n

# Release NFC pins P0.28/P0.29 for GPIO use
CONFIG_NFCT_PINS_AS_GPIOS=y

# Disable UART console - frees P1.11 (D6/TX) for use as col 2 GPIO
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
